upstream backend_servers {
    
    #if server fails the this will mark it as down for 5 seconds
    server primary-server:80 max_fails=1 fail_timeout=5s;
    
    #this is backup recovery server which is always ready
    server recovery-server:80 backup;
}

server {
    listen 80;
    location / {
        proxy_pass http://backend_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
